# Simple Linear Regression 

## Importing Libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing Data Set

In [8]:
data_set=pd.read_csv('salary.csv')
X=data_set.iloc[:,0:1].values
y=data_set.iloc[:,1:].values

In [10]:
print(X)


[[1. ]
 [1.2]
 [1.6]
 [2. ]
 [2.3]
 [2.8]
 [3. ]
 [3.3]
 [3.6]
 [3.6]
 [4. ]
 [4.1]
 [4.4]
 [4.5]
 [4.9]
 [5.1]
 [5.3]
 [5.9]
 [6.1]
 [6.7]
 [6.9]
 [7.1]
 [7.3]
 [7.5]
 [7.7]]


In [11]:
print(y)

[[325000]
 [361259]
 [340000]
 [414101]
 [405000]
 [500000]
 [495000]
 [541000]
 [568190]
 [640000]
 [610000]
 [626710]
 [690101]
 [680000]
 [760000]
 [800000]
 [780000]
 [840000]
 [860000]
 [900000]
 [930000]
 [920000]
 [910000]
 [931910]
 [951010]]


## Splitting into test and training set

In [13]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [19]:
print(X_test)

[[3.6]
 [5.3]
 [1. ]
 [7.5]
 [4.1]
 [3.6]
 [4.5]
 [1.2]]


In [20]:
print(X_train)

[[7.3]
 [2.8]
 [1.6]
 [4.4]
 [5.1]
 [2. ]
 [2.3]
 [6.9]
 [5.9]
 [7.1]
 [6.1]
 [7.7]
 [3.3]
 [4. ]
 [4.9]
 [6.7]
 [3. ]]


In [21]:
print(y_test)

[[568190]
 [780000]
 [325000]
 [931910]
 [626710]
 [640000]
 [680000]
 [361259]]


In [22]:
print(y_train)

[[910000]
 [500000]
 [340000]
 [690101]
 [800000]
 [414101]
 [405000]
 [930000]
 [840000]
 [920000]
 [860000]
 [951010]
 [541000]
 [610000]
 [760000]
 [900000]
 [495000]]


## Training on Training Set using Simple Linear Regression

## Prediction on Test Set

## Visualizing the Training Set

## Visualizing the Test Set