In [3]:
import numpy as np
import pandas as pd

In [12]:
Row=int(input("enter the number of rows"))
Col=int(input("enter the number of col"))
list1=[int(i) for i in input().split()]
print("List in 1D",list1)
list2=[]
for i in range(Row):
    list2.append([])
    for j in range(Col):
        list2[i].append(list1[Col*i+j])
print("List in 2D",list2)        

List in 1D [1, 2, 3, 4]
List in 2D [[1, 2], [3, 4]]


In [19]:
#even col will be traversed top to bottom and odd col will be traversed bottom to up
list3=[[1,2,3],[4,5,6],[7,8,9]]
for i in range(3):
    for j in range(3):
        if i%2==0:
            print(list3[j][i] ,end="")
        else :
            print(list3[2-j][i],end="")
    print()        

147
852
369


In [20]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [24]:
x=np.array([1,2,3,"xyz"])
x.dtype

dtype('<U21')

In [25]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])