In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [38]:
df=pd.read_csv('stockdata.csv')

In [14]:
df.head()

,Open,Volume,Close
0,184.267813,304285.0,206.686554
1,201.091820,137064.0,203.411346
2,202.087329,159993.0,203.351624
3,204.078332,109217.0,194.670822
4,198.095360,40982.0,194.650909


In [39]:
X=df.iloc[1:248,:2].values
y=df.iloc[1:248,2:].values

In [20]:
X

array([[2.01091820e+02, 1.37064000e+05],
       [2.02087329e+02, 1.59993000e+05],
       [2.04078332e+02, 1.09217000e+05],
       [1.98095360e+02, 4.09820000e+04],
       [1.98871852e+02, 5.10220000e+04],
       [1.93127785e+02, 6.58830000e+04],
       [1.86338440e+02, 0.00000000e+00],
       [1.98105308e+02, 1.47127000e+05],
       [2.01091824e+02, 7.50220000e+04],
       [2.01738889e+02, 6.84200000e+04],
       [2.07064855e+02, 1.45695000e+05],
       [2.05073838e+02, 1.45681000e+05],
       [2.01350647e+02, 7.80740000e+04],
       [1.90738580e+02, 1.28974000e+05],
       [1.93227347e+02, 1.15354000e+05],
       [1.90141286e+02, 1.64514000e+05],
       [2.06069340e+02, 7.32930000e+04],
       [2.06387906e+02, 7.48160000e+04],
       [2.03690093e+02, 1.46828000e+05],
       [1.79190740e+02, 1.72631000e+05],
       [1.97109815e+02, 8.41000000e+04],
       [1.90041719e+02, 4.55040000e+04],
       [1.95716107e+02, 4.34830000e+04],
       [1.98214819e+02, 8.43070000e+04],
       [2.042276

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [41]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [42]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [43]:
y_pred=model.predict(X_test)

In [44]:
from sklearn.metrics import r2_score

print(r2_score(y_test,y_pred)*100)

91.7351574688692


In [45]:
a=np.dstack((y_test,y_pred))

In [46]:
a

array([[[229.67276001, 229.8067765 ]],

       [[244.33000183, 235.83181015]],

       [[195.91999817, 193.20673676]],

       [[208.86000061, 215.33029848]],

       [[219.02084351, 219.93980106]],

       [[192.7893219 , 198.08094661]],

       [[222.16664124, 220.86732769]],

       [[190.47000122, 189.93714993]],

       [[219.75752258, 224.08056106]],

       [[188.36000061, 188.59641834]],

       [[210.50999451, 210.17170616]],

       [[200.20582581, 200.2536323 ]],

       [[217.71000671, 206.03088646]],

       [[206.83000183, 205.61176992]],

       [[191.21000671, 191.64319032]],

       [[221.39015198, 216.15094684]],

       [[258.58218384, 232.85529389]],

       [[233.41584778, 221.07538162]],

       [[171.02000427, 169.22121589]],

       [[167.42999268, 170.35665947]],

       [[194.27261353, 195.04522256]],

       [[173.77000427, 179.79307778]],

       [[231.92999268, 229.40054966]],

       [[216.5818634 , 218.54825979]],

       [[213.97364807, 203.34070189]],



In [47]:
coef=model.coef_
contribution=np.abs(coef)/np.sum(np.abs(coef))
print(contribution)

[[0.93307033 0.06692967]]
